import{a as I,i as u,S as v}from"./assets/vendor-BGz2EIcA.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(o){if(o.ep)return;o.ep=!0;const a=s(o);fetch(o.href,a)}})();const B="44952732-afe4551e0894d66c0b6ee4476";async function p(r,t=1,s=15){const n=`https://pixabay.com/api/?key=${B}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${s}`;try{return(await I.get(n)).data}catch(o){throw new Error(o.response.status)}}function L(){u.show({message:"Sorry, there are no images matching your search query. Please try again!",class:"toast-style",messageColor:"white",titleColor:"white",iconColor:"white"})}function f(){u.info({title:"Info",message:"No images found.",class:"toast-style",messageColor:"white",titleColor:"white",iconColor:"white"})}function g({webformatURL:r,largeImageURL:t,tags:s,likes:n,views:o,comments:a,downloads:i}){return`
  <div class ="image-container">
    <a href="${t}" class = "image-link">

    <li class="image-item">
      <img src="${r}" alt="${s}" />
    </li>
    <div class ="">
      <li class="image-item-info">
        <p><span class = "comment-head">Likes</span> ${n}</p>
        <p><span class = "comment-head">Views</span> ${o}</p>
        <p><span class = "comment-head">Comments</span> ${a}</p>
        <p><span class = "comment-head">Downloads</span> ${i}</p>
      </li>
    </div>
    </a>
  </div>
  `}function y(){u.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}const e={submitBtn:document.querySelector(".js-submit-btn"),form:document.querySelector("form[data-form]"),input:document.querySelector("input[data-input]"),gallery:document.querySelector(".gallery"),loading:document.querySelector(".loadingText"),loadMoreBtn:document.querySelector(".js-loadmore-btn")},h=new v(".image-link",{captions:!0,captionSelector:"img",captionsData:"alt",captionType:"attr",captionPosition:"bottom",captionDelay:250});let l=1;const b=15;let d="",m=0,c=0;function S(r){return r===""?(e.submitBtn.disabled=!0,L(),!0):(e.submitBtn.disabled=!1,!1)}function $(r){const t=r.hits;let s="";t.forEach(n=>{s+=g(n)}),e.gallery.innerHTML=s,h.refresh(),c+=t.length,c>=m?(e.loadMoreBtn.style.display="none",y()):e.loadMoreBtn.style.display="flex",M()}function w(){iziToast.error({title:"Error",message:"No Images found or an error occurred while fetching images."})}async function E(r){r.preventDefault(),e.loadMoreBtn.style.display="none";const t=e.input.value.trim(),s=e.input.value;if(d!==t&&(l=1,d=t,c=0),e.gallery.innerHTML="",e.form.reset(),S(t)){e.submitBtn.disabled=!1;return}e.loading.style.display="block";try{const n=await p(s,l,b);if(m=n.totalHits,e.loading.style.display="none",n.hits.length===0){f();return}$(n),e.gallery.style.display="flex",l+=1}catch{e.loading.style.display="none",w()}}async function q(){e.loading.style.display="block";try{const r=await p(d,l,b);if(e.loading.style.display="none",r.hits.length===0){f();return}const t=r.hits;let s="";t.forEach(n=>{s+=g(n)}),e.gallery.insertAdjacentHTML("beforeend",s),h.refresh(),c+=t.length,c>=m?(e.loadMoreBtn.style.display="none",y()):e.loadMoreBtn.style.display="flex",M(),l+=1}catch{e.loading.style.display="none",w()}}function M(){const r=document.querySelectorAll(".gallery .image-item");if(r.length>0){let t=0;r.forEach(s=>{t+=s.getBoundingClientRect().height}),window.scrollBy({top:t,behavior:"smooth"})}}e.form.addEventListener("submit",E);e.loadMoreBtn.addEventListener("click",q);
//# sourceMappingURL=index.js.map
